version: "3.3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web0
      - web1
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
  web0:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/src
    depends_on:
      - redis
  web1:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./web:/usr/src
    depends_on:
      - redis

