version: "3.3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "3080:80"
      - "3443:443"
    depends_on:
      - web0
      - web1
    environment:
      - MODE=development
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    environment:
      - MODE=development
  web0:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/src
    depends_on:
      - redis
    environment:
      - MODE=development
  web1:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./web:/usr/src
    depends_on:
      - redis
    environment:
      - MODE=development

