version: "3.3"
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:80"

